:scheduled:
  revoke_expired_subscriptions:
    cron: "0 */6 * * *"   # Every 6 hours
    class: "RevokeExpiredSubscriptionsJob"
    queue: default
    description: "Revoke expired WireGuard subscriptions"
